spring:
  application:
    name: Payment Requests
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USER}
    password: ${R2DBC_PASSWORD}
    pool:
        max-size: 20  # Maximum number of connections in the pool
        initial-size: 5 # Initial number of connections in the pool
        validation-query: SELECT 1  -- Validates connections before use

