spring:
  application:
    name: pagos360
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pagos360
    username: postgres
    password: postgres
    pool:
        max-size: 20  # Maximum number of connections in the pool
        initial-size: 5 # Initial number of connections in the pool
        validation-query: SELECT 1  -- Validates connections before use

